### ISSUE TITLE
CreateServiceProvider extension does not inject services from IServiceCollection correctly

### ISSUE THREAD

**Issue by jakubbloksa** [seesharper/LightInject.Microsoft.DependencyInjection#27]
I was updating my NuGet packages for my solution and came across an issue with CreateServiceProvider extension in version of LightInject.Microsoft.DependencyInjeciton 2.0.7 and 2.0.6. -> 2.0.5 works well.
_I am using LightInject (5.1.5) and LightInject.Intercetption (2.0.1)_

When I try to add **collection** (e.g. IEnumerable) of _"IDataContextFactory"_ (custom factory interface) the result collection is initialized, but **always empty**

When adding my data access services in Startup I have following code:
```
/// <summary>
/// Adds configuration to the service collection.
/// </summary>
/// <param name="services">The collection of services.</param>
/// <param name="configuration">The service configuration.</param>
/// <returns>The collection of services with added data access.</returns>
public static IServiceCollection AddDataAccess(this IServiceCollection services, IConfiguration configuration)
{
    services.AddEntityFrameworkSqlServer();
    services.AddDbContext<DomainDatabaseContext>(options => options.UseSqlServer(configuration.GetConnectionString("DomainDatabase")), ServiceLifetime.Transient);
    services.AddDbContext<IdentityDatabaseContext>(options => options.UseSqlServer(configuration.GetConnectionString("IdentityDatabase")));

    services.AddSingleton<IEnumerable<IDataContextFactory>>(provider => new[] { new DelegateDataContextFactory(provider.GetService<DomainDatabaseContext>) });
    services.AddSingleton<IDataContextProvider, UnitOfWorkDataContextProvider>();
    services.AddSingleton<IUnitOfWorkProvider, UnitOfWorkProvider>();
    services.AddSingleton(typeof(IUnitOfWorkStore<>), typeof(HttpContextUnitOfWorkStore<>));

    return services;
}
```

The lambda expression inside this is never called when calling CreateServiceProvider with v2.0.6 and v2.0.7

```
services.AddSingleton<IEnumerable<IDataContextFactory>>(provider => new[] { new DelegateDataContextFactory(provider.GetService<DomainDatabaseContext>) });
```

In my Startup I call ConfigureServices like this with my own extension of CreateServiceProvider

```
/// <summary>
/// This method gets called by the runtime. Use this method to add services to the container.
/// </summary>
/// <param name="services">The collection of the services.</param>
/// <returns>The provider of the service.</returns>
public IServiceProvider ConfigureServices(IServiceCollection services)
{
    // add mvc services
    services.AddHttpContextAccessor()
            .AddMvc(options =>
            {
                options.ReturnHttpNotAcceptable = true;

                options.Filters.Add(new ConsumesAttribute(MimeTypeConstants.ApplicationJson));
                options.Filters.Add(new ProducesAttribute(MimeTypeConstants.ApplicationJson));

                options.CacheProfiles.Add(
                    CacheProfiles.Codebook,
                    new CacheProfile()
                    {
                        Duration = (int)TimeSpan.FromDays(1).TotalSeconds
                    });
            })
            .AddControllersAsServices()
            .AddJsonOptions(options =>
            {
                options.SerializerSettings.Converters.Add(new StringEmptyToNullConverter());
                options.SerializerSettings.Converters.Add(new StringEnumConverter(true));
            });

    // ... (add response compression services)

    // add application services (here I add my services, e.g. Data access)
    services.AddDataAccess(configuration);

    // initialize container
    serviceProvider = services.CreateServiceProvider();

    return serviceProvider;
}
```

My ServiceProvider extension looks like this:
```
/// <summary>
/// The service provider extensions of the service collection.
/// </summary>
public static partial class IServiceCollectionExtensions
{
    // ... (some more code here)

    /// <summary>
    /// Creates service provider for the service collection.
    /// </summary>
    /// <param name="services">The collection of services.</param>
    /// <returns>The collection of services with created service provider.</returns>
    public static IServiceProvider CreateServiceProvider(this IServiceCollection services)
    {
        var container = CreateNewServiceProvider();

        // ... (some interception here)

        // logging...
        container.Initialize(
            registration => registration.ImplementingType.IsAssignableTo(typeof(ILoggingInitializer)),
            (factory, instance) => ((ILoggingInitializer)instance).SetLogger(factory.GetInstance<ILoggerFactory>()));

        return container.CreateServiceProvider(services);
    }

    /// <summary>
    /// Creates new service provider.
    /// </summary>
    /// <returns>Created service container.</returns>
    private static IServiceContainer CreateNewServiceProvider()
    {
        return new ServiceContainer(new ContainerOptions
        {
            EnablePropertyInjection = false,
            LogFactory = type => logEntry => Debug.WriteLine(logEntry.Message)
        })
        {
            ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider()
        };
    }
}
```

When I try to access these services when debugging for instance with code like this:
```
serviceProvider.GetService<IEnumerable<IDataContextFactory>>()
``` 
it always returns empty collection... As said earlier with v2.0.5 works totally fine.

Any ideas what could be wrong?

**Comment by seesharper** [comment]
Found it. It does not work when the `IEnumerable<T>` is registered with a name 

```
container.Register<IEnumerable<Foo>>(f => new[] { new Foo() },"NamedCollection");
var list = container.GetInstance<IEnumerable<Foo>>();
```

This yields an empty list. The bug is actually in LightInject itself. Looking into it.

**Comment by seesharper** [comment]
Try bumping to LightInject 5.1.6

**Comment by jakubbloksa** [comment]
LightInject 5.1.6 + LightInject.Microsoft.DependencyInjection 2.0.7 right? I am on it.

**Comment by seesharper** [comment]
Right 👍

**Comment by jakubbloksa** [comment]
Described issue is gone now, but I came across some new issues. Again it is not working with LightInject.Microsoft.DependencyInjection 2.0.7 and 2.0.6 (with 2.0.5 it works well). It seems like there is a problem with registration, too. Similar behaviour happens in two separate projects (Backend and Frontend).
I try to register some services, for example like this:
```
services.AddSingleton<LocalizedDescriptionResolver>();
services.AddAutoMapper();
```
For mapping of my models I use AutoMapper ->
The implementation of AddAutoMapper extension is in [here](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs).

When using v2.0.7 the configuration provider is probably improperly injected into the Mapper...
Maybe the problem is within this form of registration in AddAutoMapper()?

```
services.AddScoped<IMapper>(sp => new Mapper(sp.GetRequiredService<IConfigurationProvider>(), sp.GetService));
```
In my other (Frontend) project there was a problem in Configure() between these lines...

```
        public void Configure(IApplicationBuilder app, IMapper autoMapper)
        {
            // ... some code

            app.UseRequestLocalization()
               .UseAuthentication()
               .UseResponseCompression()
               .UseStatusCodePagesWithReExecute("/Error/{0}")
               .UseStaticFiles()
               .UseMvc(routes => routes.MapRoutes());
        }
```
All of it is Microsoft.AspNetCore.Builder extensions... (So this one could lead somewhere else... but also happens for me only v2.0.6+ ... routes.MapRoutes() is never called though.)
It threw many exceptions like this:

> No resolvable constructor found for Type: Microsoft.AspNetCore.Mvc.DataAnnotations.Internal.MvcDataAnnotationsMvcOptionsSetup'

It is really odd problem. Hard to tell if it is because of translation of .NET Core registrations into yours, or something else.

**Comment by seesharper** [comment]
> When using v2.0.7 the configuration provider is probably improperly injected into the Mapper..

Does it throw? I did a quick test trying to inject `IMapper` into a controller and that went just fine. 

> All of it is Microsoft.AspNetCore.Builder extensions... (So this one could lead somewhere else... but also happens for me only v2.0.6+ ... routes.MapRoutes() is never called though.)

On my end this gets called although I don't have the `MapRoutes` method available I can see that it enters the lambda function. 

The best would probably to create a simple project from where we can investigate further. I can up my test web app here on GitHub if you would like that

**Comment by jakubbloksa** [comment]
> When using v2.0.7 the configuration provider is probably improperly injected into the Mapper..

It throws an exception inside of AutoMapper - when trying to Map by using custom Converter with custom Resolver... 
Problem is that the configuration probably cannot resolve that custom Resolver, so it throws this inside MappingOperationOptions (AutoMapper's class):

> 'Cannot create an instance of type LocalizedDescriptionResolver'

There is a lot of code behind it, so if you can up your test web app, I could try to set the situation up.

In short, here is at least something for now. I create my map profile like this:

```
CreateMap(typeof(IPagedList<>), typeof(IDataPage<>)).ConvertUsing(typeof(PagedListToDataPageConverter<,>));
CreateMap<ICodebookEntityWithDescription, Model.CodebookWithDescription>()
                .ForMember(d => d.Description, options => options.ResolveUsing<LocalizedDescriptionResolver>());

```

Custom converter here

```
/// <summary>
/// The converter for paged list to data page conversion.
/// </summary>
/// <typeparam name="TSource">The type of the source.</typeparam>
/// <typeparam name="TDestination">The type of the destination.</typeparam>
public class PagedListToDataPageConverter<TSource, TDestination> : ITypeConverter<IPagedList<TSource>, IDataPage<TDestination>>
{
    private readonly IMapper mapper;

    /// <summary>
    /// Initializes a new instance of the <see cref="PagedListToDataPageConverter{TSource, TDestination}" /> class.
    /// </summary>
    /// <param name="mapper">The auto mapper.</param>
    public PagedListToDataPageConverter(IMapper mapper)
    {
        this.mapper = mapper;
    }

    /// <inheritdoc />
    public IDataPage<TDestination> Convert(IPagedList<TSource> source, IDataPage<TDestination> destination, ResolutionContext context)
    {
        if (source == null)
        {
            return null;
        }

        return new StaticDataPage<TDestination>(mapper.Map<IList<TDestination>>(source), source.PageNumber, source.PageSize, source.TotalCount);
    }
```

Custom resolver here

```
/// <summary>
/// Value resolver for getting localized description of a codebook.
/// </summary>
public class LocalizedDescriptionResolver : IValueResolver<ICodebookEntityWithDescription, CodebookWithDescription, string>
{
    /// <summary>
    /// Gets the localized description by the resource key, or default.
    /// </summary>
    /// <param name="source">The source of the mapping.</param>
    /// <param name="destination">The destination of the mapping.</param>
    /// <param name="member">The member of destination.</param>
    /// <param name="context">Resolution context.</param>
    /// <returns>Localized description.</returns>
    public string Resolve(ICodebookEntityWithDescription source, CodebookWithDescription destination, string member, ResolutionContext context)
    {
        return ResourceCodebooks.ResourceManager.GetString(source.ResourceKey) ?? source.Description;
    }
}
```

Then I call mapping like this... 
```
public IDataPage<Language> Search(LanguageSearchSettings languageSearchSettings)
{
    using (UnitOfWorkProvider.Create())
    {
        var settings = Mapper.Map<LanguageSearchSettings, CodebookSearchSettings>(languageSearchSettings);
        var foundPage = languageRepository.FindBySearchSettings(settings);

        return Mapper.Map<IPagedList<Entity.Language>, IDataPage<Language>>(foundPage);
    }
}
```
I don't know if this will help you, so... The best option will be that test web app imo.

**Comment by jakubbloksa** [comment]
I've created pull request in [here](https://github.com/seesharper/TestWebApp/pull/1)
Sorry that it took me a while, I had some problems with Git Extensions to GitHub authentication.

I've added a few models + custom converter, resolver and mapping profile.
I've tried to simplify it as possible, but still retain the similarity with my project.

I hope this will help.

**Comment by seesharper** [comment]
Try changing your container options to this

```
var serviceContainer = new ServiceContainer(new ContainerOptions
            {
                EnablePropertyInjection = false,
                LogFactory = type => logEntry => Debug.WriteLine(logEntry.Message),
                DefaultServiceSelector = s => s.Last()
            })
            {
                ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider()
            };
```

**Comment by seesharper** [comment]
The reason that you need the `DefaultServiceSelector` is that we have changed how a default services is resolved. By default service we mean the service that should be resolved in the case where there are multiple registrations with the same service type (interface).

**Comment by jakubbloksa** [comment]
It works as a charm for both of my project. Thank you for your time.
But, It is still not clear to me why we need to specify `DefaultServiceSelector`... 
I don't think I have multiple registrations with the same service type (interface). 
For example within TestWebApp project. Am I incorrect?

**Comment by seesharper** [comment]
@jakubbloksa We have another problem though. I don't know if you have noticed, but the startup time is much longer when using LightInject. I started to look at the memory consumption and it uses five times as much memory when using LightInject. That is not good at all. I've modified the project  so that it uses the source versions of LightInject and LightInject.Microsoft.DependencyInjection. You are welcome to take a look at it. If you take a memory snapshot (VS 15.8.0 Preview 5), you should see something like this 

![image](https://user-images.githubusercontent.com/1034073/43951861-910a6782-9c94-11e8-82bb-c5f787b94373.png)

**Comment by seesharper** [comment]
@jakubbloksa Took at quick stab at this. When using LightInject.Microsoft.DependencyInjection > 2.0.6 it uses an insane amount of memory. With 2.0.5 its normal. This means that there is something not related to LightInject itself, but something in LightInject.Microsoft.DependencyInjection. I'll will look further into this.

**Comment by jakubbloksa** [comment]
Oh, ok. I will check that. Let me know if you will have further information.

**Comment by seesharper** [comment]
@jakubbloksa I've updated the test web app so that you can easily switch between the scenario where it behaves normally and when it consumes a lot of memory. 

https://github.com/seesharper/TestWebApp/blob/5c7ee7c3308eeaa3d1a5fb96a77bc6e0c3b6a859/TestWebApp/Startup.cs#L40

What I have found so far is that it is related to resolving `IEnumerable<T>` and the switch toggles between the way we used to handle enumerables and the way it is handled now in `LightInject.Microsoft.DependencyInjection`.

**Comment by seesharper** [comment]
https://github.com/seesharper/LightInject/issues/434
